---
version: '2'

networks:
  tig:

services:
  influxdb:
    image: influxdb:1.7.2
    container_name: influxdb
    expose:
      - 8086
      - 8083
    networks:
      - tig

  telegraf:
    image: telegraf:1.9.1
    container_name: telegraf
    volumes:
      - ${PWD}/configs/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - "influxdb"
    networks:
      - tig

  telegraf.snmp:
    image: telegraf-snmp
    container_name: telegraf-snmp
    volumes:
      - ${PWD}/configs/telegraf.snmp.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - "influxdb"
    networks:
      - tig

  grafana:
    image: grafana/grafana:5.4.2
    container_name: grafana
    ports:
      - "9081:3000"
    volumes:
      - ${PWD}/configs/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - ${PWD}/configs/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ${PWD}/dashboards:/var/tmp/dashboards
    depends_on:
      - "telegraf"
    networks:
      - tig
