{
 "title": "SNMP dashboards",
 "description": "Monitor BGP and Interfaces and system details using SNMP",
 "tags": [
  "snmp",
  "bgp",
  "interfaces",
  "uptime",
  "inventory"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "bgpPeerRemoteAddr",
    "query": "SHOW TAG VALUES FROM \"snmp_BGP\" with KEY = \"bgpPeerRemoteAddr\""
   },
   {
    "name": "ifName",
    "query": "SHOW TAG VALUES FROM \"snmp_interfaces_statistics\" with KEY = \"ifName\""
   },
   {
    "name": "hostnames",
    "query": "SHOW TAG VALUES FROM \"snmp_BGP\" with KEY = \"hostname\""
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Inventory",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "snmp_snmp",
     "select": [
      [
       { "params": [ "jnxBoxDescr" ], "type": "field" },
       { "params": [ "HW model" ], "type": "alias" }
      ],
      [
       { "params": [ "jnxBoxInstalled" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "uptime" ], "type": "alias" }
      ],
      [
       { "params": [ "jnxBoxSerialNo" ], "type": "field" },
       { "params": [ "SN" ], "type": "alias" }
      ],
      [
       { "params": [ "sysApplInstallPkgVersion" ], "type": "field" },
       { "params": [ "SW release" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime - device $hostnames",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3.4285714285714284, "x": 0, "y": 10 },
   "repeat": "hostnames",
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_snmp",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime - device $hostnames",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3.4285714285714284, "x": 3.4285714285714284, "y": 10 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_snmp",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime - device $hostnames",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3.4285714285714284, "x": 6.857142857142857, "y": 10 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_snmp",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime - device $hostnames",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3.4285714285714284, "x": 10.285714285714285, "y": 10 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_snmp",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime - device $hostnames",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3.4285714285714284, "x": 13.714285714285714, "y": 10 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_snmp",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime - device $hostnames",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3.4285714285714284, "x": 17.142857142857142, "y": 10 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_snmp",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime - device $hostnames",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 3.4285714285714284, "x": 20.57142857142857, "y": 10 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_snmp",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" }
     ]
    }
   ]
  },
  { "title": "BGP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "BGP Peers  - Device $hostnames",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "repeat": "hostnames",
   "targets": [
    {
     "alias": "peer $tag_bgpPeerRemoteAddr",
     "groupBy": [
      { "params": [ "bgpPeerRemoteAddr" ], "type": "tag" }
     ],
     "measurement": "snmp_BGP",
     "select": [
      [
       { "params": [ "bgpPeerState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "session state" ], "type": "alias" }
      ],
      [
       { "params": [ "bgpPeerRemoteAs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "remote AS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "bgpPeerRemoteAddr", "operator": "=~", "value": "/^$bgpPeerRemoteAddr$/" }
     ]
    }
   ]
  },
  {
   "title": "BGP Peers  - Device $hostnames",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "alias": "peer $tag_bgpPeerRemoteAddr",
     "groupBy": [
      { "params": [ "bgpPeerRemoteAddr" ], "type": "tag" }
     ],
     "measurement": "snmp_BGP",
     "select": [
      [
       { "params": [ "bgpPeerState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "session state" ], "type": "alias" }
      ],
      [
       { "params": [ "bgpPeerRemoteAs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "remote AS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "bgpPeerRemoteAddr", "operator": "=~", "value": "/^$bgpPeerRemoteAddr$/" }
     ]
    }
   ]
  },
  {
   "title": "BGP Peers  - Device $hostnames",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "alias": "peer $tag_bgpPeerRemoteAddr",
     "groupBy": [
      { "params": [ "bgpPeerRemoteAddr" ], "type": "tag" }
     ],
     "measurement": "snmp_BGP",
     "select": [
      [
       { "params": [ "bgpPeerState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "session state" ], "type": "alias" }
      ],
      [
       { "params": [ "bgpPeerRemoteAs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "remote AS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "bgpPeerRemoteAddr", "operator": "=~", "value": "/^$bgpPeerRemoteAddr$/" }
     ]
    }
   ]
  },
  {
   "title": "BGP Peers  - Device $hostnames",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "alias": "peer $tag_bgpPeerRemoteAddr",
     "groupBy": [
      { "params": [ "bgpPeerRemoteAddr" ], "type": "tag" }
     ],
     "measurement": "snmp_BGP",
     "select": [
      [
       { "params": [ "bgpPeerState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "session state" ], "type": "alias" }
      ],
      [
       { "params": [ "bgpPeerRemoteAs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "remote AS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "bgpPeerRemoteAddr", "operator": "=~", "value": "/^$bgpPeerRemoteAddr$/" }
     ]
    }
   ]
  },
  {
   "title": "BGP Peers  - Device $hostnames",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "alias": "peer $tag_bgpPeerRemoteAddr",
     "groupBy": [
      { "params": [ "bgpPeerRemoteAddr" ], "type": "tag" }
     ],
     "measurement": "snmp_BGP",
     "select": [
      [
       { "params": [ "bgpPeerState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "session state" ], "type": "alias" }
      ],
      [
       { "params": [ "bgpPeerRemoteAs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "remote AS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "bgpPeerRemoteAddr", "operator": "=~", "value": "/^$bgpPeerRemoteAddr$/" }
     ]
    }
   ]
  },
  {
   "title": "BGP Peers  - Device $hostnames",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "targets": [
    {
     "alias": "peer $tag_bgpPeerRemoteAddr",
     "groupBy": [
      { "params": [ "bgpPeerRemoteAddr" ], "type": "tag" }
     ],
     "measurement": "snmp_BGP",
     "select": [
      [
       { "params": [ "bgpPeerState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "session state" ], "type": "alias" }
      ],
      [
       { "params": [ "bgpPeerRemoteAs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "remote AS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "bgpPeerRemoteAddr", "operator": "=~", "value": "/^$bgpPeerRemoteAddr$/" }
     ]
    }
   ]
  },
  {
   "title": "BGP Peers  - Device $hostnames",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "alias": "peer $tag_bgpPeerRemoteAddr",
     "groupBy": [
      { "params": [ "bgpPeerRemoteAddr" ], "type": "tag" }
     ],
     "measurement": "snmp_BGP",
     "select": [
      [
       { "params": [ "bgpPeerState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "session state" ], "type": "alias" }
      ],
      [
       { "params": [ "bgpPeerRemoteAs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "remote AS" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "bgpPeerRemoteAddr", "operator": "=~", "value": "/^$bgpPeerRemoteAddr$/" }
     ]
    }
   ]
  },
  { "title": "Interfaces status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Interfaces status - device $hostnames",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 35 },
   "repeat": "hostnames",
   "targets": [
    {
     "alias": "$tag_ifName",
     "groupBy": [
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifOperStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "op state" ], "type": "alias" }
      ],
      [
       { "params": [ "ifAdminStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "admin state" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interfaces status - device $hostnames",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 35 },
   "targets": [
    {
     "alias": "$tag_ifName",
     "groupBy": [
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifOperStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "op state" ], "type": "alias" }
      ],
      [
       { "params": [ "ifAdminStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "admin state" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interfaces status - device $hostnames",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 35 },
   "targets": [
    {
     "alias": "$tag_ifName",
     "groupBy": [
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifOperStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "op state" ], "type": "alias" }
      ],
      [
       { "params": [ "ifAdminStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "admin state" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interfaces status - device $hostnames",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 35 },
   "targets": [
    {
     "alias": "$tag_ifName",
     "groupBy": [
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifOperStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "op state" ], "type": "alias" }
      ],
      [
       { "params": [ "ifAdminStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "admin state" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interfaces status - device $hostnames",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 47 },
   "targets": [
    {
     "alias": "$tag_ifName",
     "groupBy": [
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifOperStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "op state" ], "type": "alias" }
      ],
      [
       { "params": [ "ifAdminStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "admin state" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interfaces status - device $hostnames",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 47 },
   "targets": [
    {
     "alias": "$tag_ifName",
     "groupBy": [
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifOperStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "op state" ], "type": "alias" }
      ],
      [
       { "params": [ "ifAdminStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "admin state" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interfaces status - device $hostnames",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 47 },
   "targets": [
    {
     "alias": "$tag_ifName",
     "groupBy": [
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifOperStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "op state" ], "type": "alias" }
      ],
      [
       { "params": [ "ifAdminStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "admin state" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  { "title": "Interfaces statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Interface Statistics - device $hostnames (bps)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 60 },
   "repeat": "hostnames",
   "targets": [
    {
     "alias": "$tag_ifName - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Statistics - device $hostnames (bps)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "alias": "$tag_ifName - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Statistics - device $hostnames (bps)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "alias": "$tag_ifName - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Statistics - device $hostnames (bps)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "alias": "$tag_ifName - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Statistics - device $hostnames (bps)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 108 },
   "targets": [
    {
     "alias": "$tag_ifName - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Statistics - device $hostnames (bps)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {
     "alias": "$tag_ifName - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Statistics - device $hostnames (bps)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 132 },
   "targets": [
    {
     "alias": "$tag_ifName - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Statistics - device $hostnames (unicast pps)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 144 },
   "repeat": "hostnames",
   "targets": [
    {
     "alias": "$tag_ifName - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifHCInUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Statistics - device $hostnames (unicast pps)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 156 },
   "targets": [
    {
     "alias": "$tag_ifName - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifHCInUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Statistics - device $hostnames (unicast pps)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 168 },
   "targets": [
    {
     "alias": "$tag_ifName - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifHCInUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Statistics - device $hostnames (unicast pps)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 180 },
   "targets": [
    {
     "alias": "$tag_ifName - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifHCInUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Statistics - device $hostnames (unicast pps)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 192 },
   "targets": [
    {
     "alias": "$tag_ifName - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifHCInUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Statistics - device $hostnames (unicast pps)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 204 },
   "targets": [
    {
     "alias": "$tag_ifName - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifHCInUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Statistics - device $hostnames (unicast pps)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 216 },
   "targets": [
    {
     "alias": "$tag_ifName - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifHCInUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostnames$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  }
 ]
}